name: hzfform
description: "Customized form fields and components."
version: 0.0.1
homepage: https://github.com/hiuuu/hzfform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  bidi: any
  figma_squircle: ">=0.6.3"
  flutter:
    sdk: flutter
  flutter_svg: ">=2.0.17"
  image_picker: ">=1.1.2"
  intl: ">=0.19.0"
  persian_datetime_picker: ">=3.1.0"
  provider: ">=6.1.2 <7.0.0"
  image_cropper: ">=9.0.0 <10.0.0"
  cached_network_image: ">=3.4.1 <4.0.0"
  mask_text_input_formatter: ">=2.4.0 <3.0.0"
  speech_to_text: ">=6.1.1 <7.0.0"
  dropdown_search: ">=5.0.6 <6.0.0"
  google_maps_flutter: ">=2.5.0 <3.0.0"
  geolocator: ">=10.0.1 <11.0.0"
  geocoding: ">=2.1.1 <3.0.0"
  uuid: ">=4.0.0 <5.0.0"
  qr_flutter: ">=4.1.0 <5.0.0"
  mobile_scanner: ">=3.4.1 <4.0.0"
  file_picker: ">=6.1.1 <7.0.0"
  camera: ">=0.10.5+9 <0.11.0"
  path_provider: ">=2.1.2 <3.0.0"
  image: ">=4.1.3 <5.0.0"
  open_file: ">=3.3.2 <4.0.0"
  video_compress: ">=3.1.2 <4.0.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - ic_info.svg
    - ic_trash.svg
    - ic_alret.svg

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
